addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.10.0")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.15.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"         % "0.11.1")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.6")
addSbtPlugin("io.spray"         % "sbt-revolver"         % "0.9.1")
